name: Build NextPlayer ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone source
        run: |
          git clone --depth=1 https://github.com/odkrys/nextplayer.git source

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build APK
        run: |
          cd source
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Collect arm64 APK
        run: |
          mkdir output

          find source -type f -name "*arm64-v8a*.apk" \
            -exec cp {} output/ \;

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: nextplayer-arm64
          path: output/*.apk